import { Question, Exam, Student, ExamReport, ExamVersion } from './types';

export const INITIAL_QUESTIONS: Question[] = [
  {
    id: 'q-1024',
    code: '#Q-1024',
    discipline: 'Direito Constitucional',
    difficulty: 'Médio',
    topic: 'Direitos Fundamentais',
    tags: ['TAG 1', 'TAG 2', 'TAG 3'],
    statement: 'Acerca da disciplina constitucional dos direitos e garantias fundamentais previstos no art. 5º da CF/88, assinale a alternativa correta sobre o princípio da inviolabilidade do domicílio.',
    alternatives: [
      { id: 'a1', letter: 'A', text: 'O ingresso forçado em domicílio sem consentimento do titular é admitido a qualquer hora do dia ou da noite mediante ordem da autoridade policial.' },
      { id: 'a2', letter: 'B', text: 'A casa é asilo inviolável do indivíduo, ninguém nela podendo penetrar sem consentimento do morador, salvo em caso de flagrante delito ou desastre, ou para prestar socorro, ou, durante o dia, por determinação judicial.' },
      { id: 'a3', letter: 'C', text: 'O conceito constitucional de casa restringe-se à residência fixa da pessoa natural, excluindo-se quartos de hotel e escritórios profissionais.' },
      { id: 'a4', letter: 'D', text: 'A determinação judicial para busca e apreensão domiciliar pode ser cumprida no período noturno desde que haja intimação prévia do investigado.' },
      { id: 'a5', letter: 'E', text: 'O consentimento do morador para ingresso de agentes policiais dispensa qualquer registro ou comprovação de voluntariedade.' },
    ],
    correctAlternative: 'B',
    points: 1.0,
    explanation: 'Gabarito correto: ID-2 (Alternativa B). Conforme o art. 5º, XI, da CF/88, a casa é asilo inviolável do indivíduo, com as exceções expressamente taxadas.',
  },
  {
    id: 'q-1024-2',
    code: '#Q-1024',
    discipline: 'Direito Penal',
    difficulty: 'Médio',
    topic: 'Teoria do Delito e Culpabilidade',
    tags: ['TAG 1', 'TAG 2', 'TAG 3'],
    statement: 'Em matéria de causas excludentes da culpabilidade e da ilicitude no Código Penal brasileiro, assinale a assertiva correta no que tange à coação moral irresistível e à legítima defesa.',
    alternatives: [
      { id: 'a1_2', letter: 'A', text: 'A coação moral irresistível exclui a tipicidade penal do fato praticado, isentando tanto o coator quanto o coagido.' },
      { id: 'a2_2', letter: 'B', text: 'A coação moral irresistível exclui a culpabilidade em razão da inexigibilidade de conduta diversa, respondendo pelas penas somente o autor da coação.' },
      { id: 'a3_2', letter: 'C', text: 'A legítima defesa putativa constitui causa obrigatória de extinção imediata da punibilidade sem análise do erro.' },
      { id: 'a4_2', letter: 'D', text: 'O excesso doloso na legítima defesa isenta o agente de qualquer responsabilidade penal pelo resultado excedente.' },
      { id: 'a5_2', letter: 'E', text: 'O estado de necessidade recíproco é expressamente vedado pelo ordenamento jurídico-penal brasileiro.' },
    ],
    correctAlternative: 'B',
    points: 1.0,
    explanation: 'Gabarito correto: ID-2 (Alternativa B). Art. 22 do Código Penal: sob coação irresistível, só é punível o autor da coação.',
  },
  {
    id: 'q-1024-3',
    code: '#Q-1024',
    discipline: 'Direito Civil',
    difficulty: 'Médio',
    topic: 'Responsabilidade Civil e Risco',
    tags: ['TAG 1', 'TAG 2', 'TAG 3'],
    statement: 'No âmbito do Direito Civil brasileiro, relativamente ao regime da responsabilidade civil objetiva e subjetiva disciplinada pelo Código Civil de 2002, assinale a afirmativa correta.',
    alternatives: [
      { id: 'a1_3', letter: 'A', text: 'A responsabilidade civil subjetiva dispensa a comprovação de culpa lato sensu, bastando a demonstração do dano e do nexo de causalidade.' },
      { id: 'a2_3', letter: 'B', text: 'Haverá obrigação de reparar o dano, independentemente de culpa, nos casos especificados em lei, ou quando a atividade normalmente desenvolvida pelo autor do dano implicar, por sua natureza, risco para os direitos de outrem.' },
      { id: 'a3_3', letter: 'C', text: 'O dano moral indenizável exige sempre demonstração cumulativa de reflexo patrimonial direto na esfera da vítima.' },
      { id: 'a4_3', letter: 'D', text: 'A culpa exclusiva da vítima jamais rompe o nexo de causalidade nas hipóteses legais de responsabilidade pelo risco.' },
      { id: 'a5_3', letter: 'E', text: 'A incapacidade civil relativa do agente exclui sumariamente o dever de indenizar mesmo havendo bens e patrimônio próprio.' },
    ],
    correctAlternative: 'B',
    points: 1.0,
    explanation: 'Gabarito correto: ID-2 (Alternativa B). Art. 927, parágrafo único, do CC/02 consagra a responsabilidade civil objetiva com esteio na teoria do risco.',
  },
  {
    id: 'q-1024-4',
    code: '#Q-1024',
    discipline: 'Direito Administrativo',
    difficulty: 'Médio',
    topic: 'Licitações e Contratos (Lei 14.133/21)',
    tags: ['TAG 1', 'TAG 2', 'TAG 3'],
    statement: 'De acordo com a Nova Lei de Licitações e Contratos Administrativos (Lei nº 14.133/2021), assinale a opção correta acerca das modalidades licitatórias e seus critérios de julgamento.',
    alternatives: [
      { id: 'a1_4', letter: 'A', text: 'O convite e a tomada de preços permanecem como as principais modalidades obrigatórias para contratações de menor vulto.' },
      { id: 'a2_4', letter: 'B', text: 'O diálogo competitivo é modalidade de licitação para contratação de obras, serviços e compras em que a Administração Pública realiza diálogos com licitantes previamente selecionados.' },
      { id: 'a3_4', letter: 'C', text: 'O pregão passou a ser vedado para aquisição de bens e serviços comuns de engenharia em todo território nacional.' },
      { id: 'a4_4', letter: 'D', text: 'A dispensa de licitação e a inexigibilidade possuem conceitos idênticos, não havendo critério de viabilidade de competição.' },
      { id: 'a5_4', letter: 'E', text: 'O credenciamento constitui modalidade licitatória de maior complexidade formal que o concurso e o leilão.' },
    ],
    correctAlternative: 'B',
    points: 1.0,
    explanation: 'Gabarito correto: ID-2 (Alternativa B). Art. 6º, XLII, da Lei nº 14.133/2021 define o diálogo competitivo para inovações técnicas e contratações complexas.',
  },
  {
    id: 'q-1025',
    code: '#Q-1025',
    discipline: 'Direito Penal',
    difficulty: 'Fácil',
    topic: 'Teoria Geral do Delito',
    tags: ['TAG 1', 'Direito Penal', 'TAG 2'],
    statement: 'No âmbito do Direito Penal brasileiro e segundo a teoria tripartite do crime (majoritariamente adotada pela doutrina e jurisprudência), o conceito analítico de crime é composto por:',
    alternatives: [
      { id: 'b1', letter: 'A', text: 'Fato típico, ilícito (ou antijurídico) e culpável.' },
      { id: 'b2', letter: 'B', text: 'Fato típico, antijurídico e punível.' },
      { id: 'b3', letter: 'C', text: 'Conduta voluntária, dolo direto e periculosidade.' },
      { id: 'b4', letter: 'D', text: 'Ação culposa, nexo de causalidade e imputabilidade estrita.' },
      { id: 'b5', letter: 'E', text: 'Tipicidade formal, exigibilidade de conduta e punibilidade.' },
    ],
    correctAlternative: 'A',
    points: 1.0,
    explanation: 'O conceito analítico tripartite define crime como fato típico, antijurídico (ilícito) e culpável.',
  },
  {
    id: 'q-1026',
    code: '#Q-1026',
    discipline: 'Direito Administrativo',
    difficulty: 'Difícil',
    topic: 'Poderes e Atos Administrativos',
    tags: ['TAG 2', 'Direito Administrativo', 'TAG 3'],
    statement: 'A respeito dos atributos do ato administrativo e do controle da Administração Pública, analise o princípio da autotutela consagrado nas Súmulas 346 e 473 do Supremo Tribunal Federal (STF).',
    alternatives: [
      { id: 'c1', letter: 'A', text: 'A Administração pode anular seus próprios atos apenas quando provocada pelo Poder Judiciário, respeitado o contraditório.' },
      { id: 'c2', letter: 'B', text: 'A revogação de atos administrativos alcança atos eivados de vício de ilegalidade insanável, operando efeitos retroativos ex tunc.' },
      { id: 'c3', letter: 'C', text: 'O controle judicial dos atos administrativos restringe-se exclusivamente ao mérito de conveniência e oportunidade do administrador.' },
      { id: 'c4', letter: 'D', text: 'A anulação de ato administrativo de que decorram efeitos favoráveis para os destinatários prescreve em dez anos, salvo má-fé.' },
      { id: 'c5', letter: 'E', text: 'A Administração pode anular seus próprios atos, quando eivados de vícios que os tornam ilegais, porque deles não se originam direitos; ou revogá-los, por motivo de conveniência ou oportunidade.' },
    ],
    correctAlternative: 'E',
    points: 1.0,
    explanation: 'Súmula 473 do STF: autotutela permite anulação de atos ilegais (efeito ex tunc) e revogação por conveniência e oportunidade (efeito ex nunc).',
  },
  {
    id: 'q-1027',
    code: '#Q-1027',
    discipline: 'Direito Civil',
    difficulty: 'Fácil',
    topic: 'Negócio Jurídico e Validade',
    tags: ['TAG 1', 'Direito Civil', 'TAG 3'],
    statement: 'Nos termos expressos do art. 104 do Código Civil brasileiro, a validade do negócio jurídico requer agente capaz, objeto lícito, possível, determinado ou determinável, e:',
    alternatives: [
      { id: 'd1', letter: 'A', text: 'Forma prescrita ou não defesa em lei.' },
      { id: 'd2', letter: 'B', text: 'Registro público imobiliário perante o cartório competente.' },
      { id: 'd3', letter: 'C', text: 'Reconhecimento de firma por autenticidade das partes.' },
      { id: 'd4', letter: 'D', text: 'Assistência obrigatória de advogado devidamente inscrito na OAB.' },
      { id: 'd5', letter: 'E', text: 'Homologação judicial prévia da vontade manifestada.' },
    ],
    correctAlternative: 'A',
    points: 1.0,
    explanation: 'Art. 104 do Código Civil: agente capaz, objeto lícito, possível, determinado ou determinável, e forma prescrita ou não defesa em lei.',
  },
  {
    id: 'q-1028',
    code: '#Q-1028',
    discipline: 'Direito Constitucional',
    difficulty: 'Médio',
    topic: 'Controle de Constitucionalidade',
    tags: ['TAG 1', 'TAG 2', 'Direito Constitucional'],
    statement: 'Sobre os legitimados para propositura da Ação Direta de Inconstitucionalidade (ADI) perante o Supremo Tribunal Federal, conforme o art. 103 da Constituição Federal, assinale a afirmativa correta:',
    alternatives: [
      { id: 'e1', letter: 'A', text: 'O Conselho Federal da Ordem dos Advogados do Brasil é legitimado universal, não necessitando comprovar pertinência temática.' },
      { id: 'e2', letter: 'B', text: 'As confederações sindicais são legitimadas universais, podendo questionar qualquer matéria independentemente da categoria.' },
      { id: 'e3', letter: 'C', text: 'O Governador de Estado possui legitimação universal irrestrita em sede de fiscalização abstrata perante o STF.' },
      { id: 'e4', letter: 'D', text: 'Partidos políticos com representação em qualquer Câmara Municipal possuem legitimidade ativa para propor ADI no STF.' },
      { id: 'e5', letter: 'E', text: 'Qualquer cidadão eleitor no pleno exercício dos direitos políticos pode ajuizar ADI perante o Supremo Tribunal Federal.' },
    ],
    correctAlternative: 'A',
    points: 1.0,
    explanation: 'O CFOAB (art. 103, VII, CF/88) é classificado pela jurisprudência do STF como legitimado universal ou neutro, sem exigência de pertinência temática.',
  },
  {
    id: 'q-1029',
    code: '#Q-1029',
    discipline: 'Direito Processual Civil',
    difficulty: 'Fácil',
    topic: 'Tutela Provisória',
    tags: ['TAG 3', 'Processo Civil'],
    statement: 'Segundo o Código de Processo Civil brasileiro (CPC/2015), a tutela provisória pode fundamentar-se em:',
    alternatives: [
      { id: 'f1', letter: 'A', text: 'Preclusão consumativa ou coisa julgada formal.' },
      { id: 'f2', letter: 'B', text: 'Urgência ou evidência.' },
      { id: 'f3', letter: 'C', text: 'Revelia ou julgamento antecipado do mérito.' },
      { id: 'f4', letter: 'D', text: 'Suspeição ou impedimento do magistrado prolator.' },
      { id: 'f5', letter: 'E', text: 'Incompetência absoluta ou derrogação de foro.' },
    ],
    correctAlternative: 'B',
    points: 1.0,
    explanation: 'Art. 294 do CPC: a tutela provisória pode fundamentar-se em urgência ou evidência.',
  },
  {
    id: 'q-1030',
    code: '#Q-1030',
    discipline: 'Direito Penal',
    difficulty: 'Fácil',
    topic: 'Causas Excludentes da Ilicitude',
    tags: ['TAG 1', 'TAG 2', 'Direito Penal'],
    statement: 'De acordo com o artigo 23 do Código Penal brasileiro, não há crime quando o agente pratica o fato em estado de necessidade, legítima defesa, estrito cumprimento de dever legal ou:',
    alternatives: [
      { id: 'g1', letter: 'A', text: 'Exercício regular de direito.' },
      { id: 'g2', letter: 'B', text: 'Obediência a ordem manifestamente ilegal de superior.' },
      { id: 'g3', letter: 'C', text: 'Coação física relativa com emprego de arma.' },
      { id: 'g4', letter: 'D', text: 'Embriaguez preordenada ou voluntária.' },
      { id: 'g5', letter: 'E', text: 'Erro inescusável sobre elementos constitutivos do tipo.' },
    ],
    correctAlternative: 'A',
    points: 1.0,
    explanation: 'Art. 23 do CP elenca como causas excludentes da ilicitude: estado de necessidade, legítima defesa, estrito cumprimento de dever legal e exercício regular de direito.',
  },
  {
    id: 'q-1031',
    code: '#Q-1031',
    discipline: 'Direito Civil',
    difficulty: 'Fácil',
    topic: 'Prescrição e Decadência',
    tags: ['TAG 2', 'Direito Civil', 'TAG 3'],
    statement: 'No Código Civil brasileiro de 2002, a prescrição atinge a pretensão de exigir uma prestação em juízo, ao passo que a decadência extingue:',
    alternatives: [
      { id: 'h1', letter: 'A', text: 'A capacidade processual civil das partes demandantes.' },
      { id: 'h2', letter: 'B', text: 'A personalidade civil da pessoa natural.' },
      { id: 'h3', letter: 'C', text: 'A faculdade de interposição de embargos de declaração.' },
      { id: 'h4', letter: 'D', text: 'O próprio direito potestativo em virtude do decurso do prazo fixado em lei.' },
      { id: 'h5', letter: 'E', text: 'A solidariedade passiva nas obrigações indivisíveis.' },
    ],
    correctAlternative: 'D',
    points: 1.0,
    explanation: 'A decadência atinge diretamente o direito potestativo do titular, enquanto a prescrição extingue a pretensão executória.',
  },
  {
    id: 'q-1032',
    code: '#Q-1032',
    discipline: 'Direito Tributário',
    difficulty: 'Fácil',
    topic: 'Limitações Constitucionais ao Tributar',
    tags: ['TAG 1', 'Direito Tributário', 'TAG 3'],
    statement: 'Qual postulado constitucional veda à União, aos Estados, ao Distrito Federal e aos Municípios cobrar tributos em relação a fatos geradores ocorridos antes do início da vigência da lei que os houver instituído ou aumentado?',
    alternatives: [
      { id: 'i1', letter: 'A', text: 'Princípio da Irretroatividade Tributária.' },
      { id: 'i2', letter: 'B', text: 'Princípio da Anterioridade Nonagesimal estrita.' },
      { id: 'i3', letter: 'C', text: 'Princípio da Vedação ao Efeito de Confisco.' },
      { id: 'i4', letter: 'D', text: 'Princípio da Uniformidade Geográfica da Renda.' },
      { id: 'i5', letter: 'E', text: 'Princípio da Capacidade Contributiva Presumida.' },
    ],
    correctAlternative: 'A',
    points: 1.0,
    explanation: 'Art. 150, III, "a", da CF/88 veda a cobrança de tributos sobre fatos geradores ocorridos antes da vigência da lei instituidora (irretroatividade).',
  },
  {
    id: 'q-1033',
    code: '#Q-1033',
    discipline: 'Direito do Trabalho',
    difficulty: 'Médio',
    topic: 'Relação de Emprego',
    tags: ['TAG 1', 'TAG 2', 'Direito do Trabalho'],
    statement: 'Conforme preceitua a Consolidação das Leis do Trabalho (CLT), consideram-se requisitos essenciais e cumulativos configuradores da relação de emprego entre empregado e empregador:',
    alternatives: [
      { id: 'j1', letter: 'A', text: 'Pessoalidade, não eventualidade (habitualidade), onerosidade e subordinação jurídica.' },
      { id: 'j2', letter: 'B', text: 'Eventualidade, autonomia decisória e prestação de garantia real.' },
      { id: 'j3', letter: 'C', text: 'Filiação sindical prévia, exclusividade de jornada e dolo eventual.' },
      { id: 'j4', letter: 'D', text: 'Sociedade de fato, rateio de perdas societárias e co-gestão fabril.' },
      { id: 'j5', letter: 'E', text: 'Trabalho voluntário com reembolso de despesas de transporte.' },
    ],
    correctAlternative: 'A',
    points: 1.0,
    explanation: 'Artigos 2º e 3º da CLT: pessoa física, pessoalidade, não eventualidade, onerosidade e subordinação jurídica.',
  },
  {
    id: 'q-1034',
    code: '#Q-1034',
    discipline: 'Direito Processual Penal',
    difficulty: 'Fácil',
    topic: 'Inquérito Policial',
    tags: ['TAG 1', 'Processo Penal'],
    statement: 'A respeito das características fundamentais do inquérito policial no ordenamento jurídico-processual brasileiro, assinale a afirmativa correta:',
    alternatives: [
      { id: 'k1', letter: 'A', text: 'O inquérito policial tem natureza judicial e suas conclusões vinculam o juiz.' },
      { id: 'k2', letter: 'B', text: 'Trata-se de procedimento administrativo inquisitivo, pré-processual, informativo e oficial.' },
      { id: 'k3', letter: 'C', text: 'A autoridade policial pode mandar arquivar diretamente os autos de inquérito sem manifestação do MP.' },
      { id: 'k4', letter: 'D', text: 'O contraditório prévio pleno é requisito de validade formal do inquérito sob pena de nulidade absoluta.' },
      { id: 'k5', letter: 'E', text: 'O inquérito policial é peça estritamente indispensável ao ajuizamento de qualquer denúncia penal pública.' },
    ],
    correctAlternative: 'B',
    points: 1.0,
    explanation: 'O inquérito policial é procedimento administrativo de natureza inquisitiva, pré-processual e informativo presidido pelo delegado de polícia.',
  },
  {
    id: 'q-1035',
    code: '#Q-1035',
    discipline: 'Direito Internacional',
    difficulty: 'Difícil',
    topic: 'Tratados e Direitos Humanos',
    tags: ['TAG 2', 'Direito Internacional', 'TAG 3'],
    statement: 'Conforme o § 3º do art. 5º da CF/88 (inserido pela EC nº 45/2004), os tratados e convenções internacionais sobre direitos humanos que forem aprovados, em cada Casa do Congresso Nacional, em dois turnos, por três quintos dos votos dos respectivos membros, serão equivalentes às:',
    alternatives: [
      { id: 'l1', letter: 'A', text: 'Leis complementares federais.' },
      { id: 'l2', letter: 'B', text: 'Leis ordinárias de eficácia plena.' },
      { id: 'l3', letter: 'C', text: 'Normas supralegais infraconstitucionais.' },
      { id: 'l4', letter: 'D', text: 'Emendas constitucionais.' },
      { id: 'l5', letter: 'E', text: 'Resoluções conjuntas do Congresso Nacional.' },
    ],
    correctAlternative: 'D',
    points: 1.0,
    explanation: 'Art. 5º, § 3º, da CF/88: tratados de direitos humanos aprovados pelo quórum de emenda constitucional ingressam no bloco de constitucionalidade.',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-1',
    name: 'Amanda Dolores',
    registration: '2024.1.001',
    course: 'Direito',
    email: 'amanda.dolores@universidade.edu.br',
    classGroup: 'Turma A',
    discipline: 'Direito Constitucional',
    examsTaken: 12,
    overallAverage: 9.2,
  },
  {
    id: 'std-2',
    name: 'Bruno Cortela',
    registration: '2024.1.045',
    course: 'Direito',
    email: 'bruno.cortela@universidade.edu.br',
    classGroup: 'Turma B',
    discipline: 'Direito Penal',
    examsTaken: 11,
    overallAverage: 6.8,
  },
  {
    id: 'std-3',
    name: 'Cleber Santana',
    registration: '2024.1.089',
    course: 'Direito',
    email: 'cleber.santana@universidade.edu.br',
    classGroup: 'Turma A',
    discipline: 'Direito Civil',
    examsTaken: 12,
    overallAverage: 8.5,
  },
  {
    id: 'std-4',
    name: 'Julio Balestrin',
    registration: '2024.1.102',
    course: 'Direito',
    email: 'julio.balestrin@universidade.edu.br',
    classGroup: 'Turma A',
    discipline: 'Direito Constitucional',
    examsTaken: 10,
    overallAverage: 5.5,
  },
  {
    id: 'std-5',
    name: 'Moacir Neto',
    registration: '2024.1.103',
    course: 'Direito',
    email: 'moacir.neto@universidade.edu.br',
    classGroup: 'Turma A',
    discipline: 'Direito Constitucional',
    examsTaken: 10,
    overallAverage: 7.5,
  },
  {
    id: 'std-6',
    name: 'Alberto Einstein',
    registration: '2024.1.104',
    course: 'Direito',
    email: 'alberto.einstein@universidade.edu.br',
    classGroup: 'Turma A',
    discipline: 'Direito Internacional',
    examsTaken: 10,
    overallAverage: 10.0,
  },
  {
    id: 'std-7',
    name: 'Beatriz Vasconcelos',
    registration: '2024.1.115',
    course: 'Direito',
    email: 'beatriz.v@universidade.edu.br',
    classGroup: 'Turma C',
    discipline: 'Direito Constitucional',
    examsTaken: 9,
    overallAverage: 7.8,
  },
  {
    id: 'std-8',
    name: 'Guilherme Siqueira',
    registration: '2024.1.120',
    course: 'Direito',
    email: 'guilherme.s@universidade.edu.br',
    classGroup: 'Turma B',
    discipline: 'Direito Administrativo',
    examsTaken: 12,
    overallAverage: 8.9,
  },
  {
    id: 'std-9',
    name: 'Mariana Duarte',
    registration: '2024.1.144',
    course: 'Direito',
    email: 'mariana.d@universidade.edu.br',
    classGroup: 'Turma A',
    discipline: 'Direito do Trabalho',
    examsTaken: 11,
    overallAverage: 7.4,
  },
  {
    id: 'std-10',
    name: 'Rodrigo Faro',
    registration: '2024.1.150',
    course: 'Direito',
    email: 'rodrigo.f@universidade.edu.br',
    classGroup: 'Turma D',
    discipline: 'Direito Tributário',
    examsTaken: 8,
    overallAverage: 6.8,
  },
];

const buildInitialExamVersions = (questionIds: string[], numVersions: number = 4): ExamVersion[] => {
  const selected = questionIds
    .map((id) => INITIAL_QUESTIONS.find((q) => q.id === id))
    .filter((q): q is Question => q !== undefined);

  const versionLetters: ('A' | 'B' | 'C' | 'D')[] = (['A', 'B', 'C', 'D'] as const).slice(0, numVersions);

  return versionLetters.map((versionLetter) => {
    const questions = selected.map((q, idx) => ({
      originalQuestionId: q.id,
      orderIndex: idx + 1,
      statement: q.statement,
      alternatives: q.alternatives,
      correctAlternative: q.correctAlternative,
    }));

    const answerKey: Record<number, 'A' | 'B' | 'C' | 'D' | 'E'> = {};
    questions.forEach((q, idx) => {
      answerKey[idx + 1] = q.correctAlternative;
    });

    return {
      versionLetter,
      questions,
      answerKey,
    };
  });
};

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-1',
    code: '#DIR-CONST-2024.2',
    title: 'P1 - Direito Constitucional I - 2024.2',
    subtitle: 'Faculdade Nacional de Direito — Avaliação Semestral 2024.2',
    institution: 'UNIVERSIDADE FEDERAL DO RIO DE JANEIRO',
    department: 'Faculdade Nacional de Direito | Departamento de Direito Público',
    course: 'Direito',
    discipline: 'Direito Constitucional',
    classGroup: 'Turma A',
    semester: '2024.2',
    date: '12 Mar, 2024',
    duration: '2 horas',
    instructions: 'Marque apenas uma alternativa por questão. Preencha completamente o campo correspondente. Use apenas caneta preta ou azul. Rasuras anularão a questão. Duração máxima: 2 horas. Permitida consulta apenas a textos de lei seca sem anotações.',
    status: 'Corrigida',
    shuffleQuestions: true,
    shuffleAlternatives: true,
    numberOfVersions: 4,
    selectedQuestionIds: ['q-1024', 'q-1025', 'q-1026', 'q-1027', 'q-1028', 'q-1029', 'q-1030', 'q-1031', 'q-1032', 'q-1033', 'q-1034', 'q-1035'],
    versions: buildInitialExamVersions(['q-1024', 'q-1025', 'q-1026', 'q-1027', 'q-1028', 'q-1029', 'q-1030', 'q-1031', 'q-1032', 'q-1033', 'q-1034', 'q-1035'], 4),
    maxScore: 10.0,
    totalStudents: 34,
    averageScore: 7.8,
  },
  {
    id: 'exam-2',
    code: '#DIR-PENAL-2024.2',
    title: 'P2 - Direito Penal II: Teoria das Penas',
    subtitle: 'Departamento de Ciências Penais — 2024.2',
    institution: 'UNIVERSIDADE FEDERAL DO RIO DE JANEIRO',
    department: 'Faculdade Nacional de Direito | Departamento de Ciências Penais',
    course: 'Direito',
    discipline: 'Direito Penal',
    classGroup: 'Turma B',
    semester: '2024.2',
    date: '10 Mar, 2024',
    duration: '2 horas',
    instructions: 'Responda com atenção. Preencha a folha de respostas com caneta azul ou preta. Proibida a comunicação entre alunos.',
    status: 'Pendente',
    shuffleQuestions: true,
    shuffleAlternatives: true,
    numberOfVersions: 2,
    selectedQuestionIds: ['q-1024-2', 'q-1025', 'q-1030', 'q-1034'],
    versions: buildInitialExamVersions(['q-1024-2', 'q-1025', 'q-1030', 'q-1034'], 2),
    maxScore: 10.0,
    totalStudents: 28,
    averageScore: 0,
  },
  {
    id: 'exam-3',
    code: '#SIMUL-OAB-2024.2',
    title: 'Simulado Geral OAB — 1ª Fase',
    subtitle: 'Núcleo de Prática Jurídica — Simulado Preparatório',
    institution: 'UNIVERSIDADE FEDERAL DO RIO DE JANEIRO',
    department: 'Faculdade Nacional de Direito | Núcleo de Prática Jurídica',
    course: 'Direito',
    discipline: 'Direito Civil e Constitucional',
    classGroup: 'Turma Geral',
    semester: '2024.2',
    date: '08 Mar, 2024',
    duration: '3 horas',
    instructions: 'Simulado unificado nos padrões da prova de 1ª Fase do Exame de Ordem dos Advogados do Brasil (FGV). 80 questões de múltipla escolha.',
    status: 'Corrigida',
    shuffleQuestions: true,
    shuffleAlternatives: false,
    numberOfVersions: 2,
    selectedQuestionIds: ['q-1024', 'q-1024-3', 'q-1026', 'q-1027', 'q-1028', 'q-1031', 'q-1032', 'q-1035'],
    versions: buildInitialExamVersions(['q-1024', 'q-1024-3', 'q-1026', 'q-1027', 'q-1028', 'q-1031', 'q-1032', 'q-1035'], 2),
    maxScore: 10.0,
    totalStudents: 42,
    averageScore: 8.3,
  },
  {
    id: 'exam-4',
    code: '#DIR-CIVIL-2024.2',
    title: 'P1 - Direito Civil III: Contratos e Obrigações',
    subtitle: 'Faculdade Nacional de Direito — Avaliação Semestral 2024.2',
    institution: 'UNIVERSIDADE FEDERAL DO RIO DE JANEIRO',
    department: 'Faculdade Nacional de Direito | Departamento de Direito Privado',
    course: 'Direito',
    discipline: 'Direito Civil',
    classGroup: 'Turma C',
    semester: '2024.2',
    date: '05 Mar, 2024',
    duration: '2 horas',
    instructions: 'Marque apenas uma alternativa por questão. Justifique em folha avulsa caso haja anulação pretendida.',
    status: 'Em Andamento',
    shuffleQuestions: true,
    shuffleAlternatives: true,
    numberOfVersions: 2,
    selectedQuestionIds: ['q-1024-3', 'q-1027', 'q-1031'],
    versions: buildInitialExamVersions(['q-1024-3', 'q-1027', 'q-1031'], 2),
    maxScore: 10.0,
    totalStudents: 31,
    averageScore: 7.1,
  },
  {
    id: 'exam-5',
    code: '#DIR-ADM-2024.2',
    title: 'Exame Final - Direito Administrativo e Licitações',
    subtitle: 'Avaliação Final Semestral — 2024.2',
    institution: 'UNIVERSIDADE FEDERAL DO RIO DE JANEIRO',
    department: 'Faculdade Nacional de Direito | Departamento de Direito do Estado',
    course: 'Direito',
    discipline: 'Direito Administrativo',
    classGroup: 'Turma A',
    semester: '2024.2',
    date: '02 Mar, 2024',
    duration: '2 horas',
    instructions: 'Prova teórica e prática sobre a Lei 14.133/21 e Regime Jurídico Administrativo.',
    status: 'Pendente',
    shuffleQuestions: true,
    shuffleAlternatives: true,
    numberOfVersions: 3,
    selectedQuestionIds: ['q-1024-4', 'q-1026'],
    versions: buildInitialExamVersions(['q-1024-4', 'q-1026'], 3),
    maxScore: 10.0,
    totalStudents: 36,
    averageScore: 0,
  },
];

export const INITIAL_REPORT: ExamReport = {
  examId: 'exam-1',
  examTitle: 'P1 - Direito Constitucional I - 2024.2',
  averageScore: 7.8,
  highestScore: 10.0,
  highestScorer: 'Alberto Einstein',
  lowestScore: 4.5,
  lowestScorersCount: 2,
  approvalRate: 88.2,
  totalStudents: 34,
  questionsAnalytics: [
    { questionNumber: 1, discipline: 'Direito Constitucional', difficulty: 'Médio', statementSnippet: 'Inviolabilidade do domicílio (art. 5º, XI)...', correctLetter: 'B', correctCount: 29, totalAnswers: 34, correctPercentage: 85.3, distribution: { A: 2, B: 29, C: 2, D: 1, E: 0 } },
    { questionNumber: 2, discipline: 'Direito Penal', difficulty: 'Fácil', statementSnippet: 'Conceito analítico de crime...', correctLetter: 'A', correctCount: 31, totalAnswers: 34, correctPercentage: 91.2, distribution: { A: 31, B: 1, C: 1, D: 1, E: 0 } },
    { questionNumber: 3, discipline: 'Direito Administrativo', difficulty: 'Difícil', statementSnippet: 'Princípio da autotutela (Súmula 473)...', correctLetter: 'E', correctCount: 22, totalAnswers: 34, correctPercentage: 64.7, distribution: { A: 4, B: 3, C: 3, D: 2, E: 22 } },
    { questionNumber: 4, discipline: 'Direito Civil', difficulty: 'Fácil', statementSnippet: 'Requisitos de validade do negócio jurídico...', correctLetter: 'A', correctCount: 30, totalAnswers: 34, correctPercentage: 88.2, distribution: { A: 30, B: 1, C: 2, D: 1, E: 0 } },
    { questionNumber: 5, discipline: 'Direito Constitucional', difficulty: 'Médio', statementSnippet: 'Legitimidade para propor ADI (art. 103)...', correctLetter: 'A', correctCount: 26, totalAnswers: 34, correctPercentage: 76.5, distribution: { A: 26, B: 3, C: 2, D: 2, E: 1 } },
    { questionNumber: 6, discipline: 'Direito Processual Civil', difficulty: 'Fácil', statementSnippet: 'Tutela provisória de urgência e evidência...', correctLetter: 'B', correctCount: 28, totalAnswers: 34, correctPercentage: 82.4, distribution: { A: 3, B: 28, C: 2, D: 1, E: 0 } },
    { questionNumber: 7, discipline: 'Direito Penal', difficulty: 'Fácil', statementSnippet: 'Causas excludentes de ilicitude...', correctLetter: 'A', correctCount: 32, totalAnswers: 34, correctPercentage: 94.1, distribution: { A: 32, B: 1, C: 1, D: 0, E: 0 } },
    { questionNumber: 8, discipline: 'Direito Civil', difficulty: 'Fácil', statementSnippet: 'Decadência e prescrição...', correctLetter: 'D', correctCount: 25, totalAnswers: 34, correctPercentage: 73.5, distribution: { A: 2, B: 3, C: 4, D: 25, E: 0 } },
    { questionNumber: 9, discipline: 'Direito Tributário', difficulty: 'Fácil', statementSnippet: 'Princípio da irretroatividade tributária...', correctLetter: 'A', correctCount: 27, totalAnswers: 34, correctPercentage: 79.4, distribution: { A: 27, B: 3, C: 2, D: 1, E: 1 } },
    { questionNumber: 10, discipline: 'Direito do Trabalho', difficulty: 'Médio', statementSnippet: 'Pressupostos da relação de emprego...', correctLetter: 'A', correctCount: 28, totalAnswers: 34, correctPercentage: 82.4, distribution: { A: 28, B: 2, C: 2, D: 1, E: 1 } },
    { questionNumber: 11, discipline: 'Direito Processual Penal', difficulty: 'Fácil', statementSnippet: 'Inquérito policial e natureza inquisitiva...', correctLetter: 'B', correctCount: 24, totalAnswers: 34, correctPercentage: 70.6, distribution: { A: 3, B: 24, C: 4, D: 2, E: 1 } },
    { questionNumber: 12, discipline: 'Direito Internacional', difficulty: 'Difícil', statementSnippet: 'Tratados internacionais de direitos humanos...', correctLetter: 'D', correctCount: 21, totalAnswers: 34, correctPercentage: 61.8, distribution: { A: 4, B: 4, C: 5, D: 21, E: 0 } },
  ],
  studentResults: [
    {
      studentId: 'std-1',
      studentName: 'Amanda Dolores',
      registration: '2024.1.001',
      versionLetter: 'A',
      score: 9.2,
      maxScore: 10.0,
      submittedAt: '12/03/2024 10:45',
      answers: {
        1: { chosen: 'B', correct: 'B', isCorrect: true },
        2: { chosen: 'A', correct: 'A', isCorrect: true },
        3: { chosen: 'E', correct: 'E', isCorrect: true },
        4: { chosen: 'A', correct: 'A', isCorrect: true },
        5: { chosen: 'A', correct: 'A', isCorrect: true },
        6: { chosen: 'B', correct: 'B', isCorrect: true },
        7: { chosen: 'A', correct: 'A', isCorrect: true },
        8: { chosen: 'D', correct: 'D', isCorrect: true },
        9: { chosen: 'A', correct: 'A', isCorrect: true },
        10: { chosen: 'A', correct: 'A', isCorrect: true },
        11: { chosen: 'C', correct: 'B', isCorrect: false },
        12: { chosen: 'D', correct: 'D', isCorrect: true },
      },
    },
    {
      studentId: 'std-2',
      studentName: 'Bruno Cortela',
      registration: '2024.1.045',
      versionLetter: 'A',
      score: 6.8,
      maxScore: 10.0,
      submittedAt: '12/03/2024 10:52',
      answers: {
        1: { chosen: 'B', correct: 'B', isCorrect: true },
        2: { chosen: 'A', correct: 'A', isCorrect: true },
        3: { chosen: 'E', correct: 'E', isCorrect: true },
        4: { chosen: 'B', correct: 'A', isCorrect: false },
        5: { chosen: 'A', correct: 'A', isCorrect: true },
        6: { chosen: 'B', correct: 'B', isCorrect: true },
        7: { chosen: 'A', correct: 'A', isCorrect: true },
        8: { chosen: 'C', correct: 'D', isCorrect: false },
        9: { chosen: 'A', correct: 'A', isCorrect: true },
        10: { chosen: 'A', correct: 'A', isCorrect: true },
        11: { chosen: 'B', correct: 'B', isCorrect: true },
        12: { chosen: 'A', correct: 'D', isCorrect: false },
      },
    },
    {
      studentId: 'std-3',
      studentName: 'Cleber Santana',
      registration: '2024.1.089',
      versionLetter: 'A',
      score: 8.5,
      maxScore: 10.0,
      submittedAt: '12/03/2024 11:05',
      answers: {
        1: { chosen: 'B', correct: 'B', isCorrect: true },
        2: { chosen: 'A', correct: 'A', isCorrect: true },
        3: { chosen: 'E', correct: 'E', isCorrect: true },
        4: { chosen: 'A', correct: 'A', isCorrect: true },
        5: { chosen: 'A', correct: 'A', isCorrect: true },
        6: { chosen: 'B', correct: 'B', isCorrect: true },
        7: { chosen: 'A', correct: 'A', isCorrect: true },
        8: { chosen: 'D', correct: 'D', isCorrect: true },
        9: { chosen: 'B', correct: 'A', isCorrect: false },
        10: { chosen: 'A', correct: 'A', isCorrect: true },
        11: { chosen: 'B', correct: 'B', isCorrect: true },
        12: { chosen: 'D', correct: 'D', isCorrect: true },
      },
    },
  ],
};
